server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s

database:
  user: "postgres"
  dbname: "movies_library"
  host: "postgres"
  port: 5432
  sslmode: "disable"

env_file: ".env"
logger_level: "debug"

cookie_settings:
  secure: "true"
  http_only: "true"
  expire_date:
    years: 0
    months: 0
    days: 7

page_size: 10
